### ISSUE TITLE
Link URLs

### ISSUE THREAD

**Issue by champfish** [justinpotts/pattr#6]
Pattr should link text starting with http: https: or www.

**Comment by justinpotts** [comment]
Thanks for your idea @champfish! Would you mind submitting the feature request regarding the unread messages in a separate issue?

**Comment by jeffw16** [comment]
@champfish, I have advised @justinpotts on removing http: and https: because simply having //www.blah.com/blah/blah will allow the link to be protocol-agnostic and keeps the link within the same protocol. That way, everything that is HTTPS will remain HTTPS and people on HTTP can continue using HTTP. This was an intentional feature designed into Pattr that will help the client be compatible with everybody's systems.

**Comment by jeffw16** [comment]
Never mind, I had no idea you were talking about something else. Disregard my commentary.

**Comment by champfish** [comment]
@jeffw16
